disabled_rules: # rule identifiers to exclude from running
  - line_length
  - trailing_whitespace
  - identifier_name
  - unused_closure_parameter
  - cyclomatic_complexity
  - function_body_length
  - large_tuple
  - type_body_length
  - force_cast
  - type_name
