# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  lane :tests do
    setup_ci

    clear_derived_data

    build_number = ENV['GITHUB_RUN_NUMBER'].to_i + 400

    increment_build_number(
      build_number: build_number,
    )

    sh("echo \"#{build_number}\" > build_number")

    run_tests(project: "amplience-sdk-ios-full.xcodeproj",
            devices: ["iPhone 13 Pro",])
  end

end
